{% set version = "1.1.5" %}

package:
  name: bgenix
  version: "{{ version|replace("-", "_") }}"

source:
  url: https://github.com/huntdatacenter/rbgen/releases/download/{{ version }}/bgen-{{ version }}.tar.bz2
  sha256: 5e0dd68dc4ec9fd4282fbd3164c7c4aefb9870b6e2969dad304b7a69f7a75772

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - boost {{ boost }}
    - boost-cpp {{ boost }}
    - sqlite
    - zlib
    - zstd
  host:
    - boost-cpp {{ boost }}
    - sqlite
    - zlib
    - zstd
  run:
    - boost-cpp {{ boost }}

test:
  source_files:
    - example/example.15bits.bgen
    - example/example.16bits.bgen
    - example/example.16bits.bgen.bgi
  commands:
    - bgenix -help
    - bgenix -g example/example.16bits.bgen >/dev/null
    - bgenix -g example/example.15bits.bgen -index

about:
  home: https://enkre.net/cgi-bin/code/bgen
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: Reference implementation of the BGEN format, written in C++

extra:
  recipe-maintainers:
    - matuskosut
